
import type { Metadata } from "next";
import './globals.css'


export const metadata: Metadata = {
  title: "random_videos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f0f0f0]">{children}</body>
    </html>
  );
}
